### ISSUE TITLE
Uncaught TypeError: Character index must be a number

### ISSUE THREAD

**Issue by wottpal** [atom/toggle-quotes#59]
[Enter steps to reproduce:]

Toggled quotes in a js file

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [toggle-quotes](https://github.com/atom/toggle-quotes) package 1.1.0

### Stack Trace

Uncaught TypeError: Character index must be a number

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:980

TypeError: Character index must be a number
    at SyntaxNode.descendantForIndex (/app.asar/node_modules/tree-sitter/index.js:195:19)
    at TreeSitterLanguageMode.getRangeForSyntaxNodeContainingRange (/Applications/Atom.app/Contents/Resources/app/src/tree-sitter-language-mode.js:335:41)
    at TreeSitterLanguageMode.bufferRangeForScopeAtPosition (/Applications/Atom.app/Contents/Resources/app/src/tree-sitter-language-mode.js:343:23)
    at TextEditor.bufferRangeForScopeAtPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3867:48)
    at toggleQuoteAtPosition (/packages/toggle-quotes/lib/toggle-quotes.js:26:22)
    at /packages/toggle-quotes/lib/toggle-quotes.js:7:7
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:973:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2002:30)
    at toggleQuotes (/packages/toggle-quotes/lib/toggle-quotes.js:4:10)
    at /packages/toggle-quotes/lib/main.js:13:9)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -2:02.2.0 intentions:highlight (input.hidden-input)
     -2:02.0 editor:move-to-end-of-word (input.hidden-input)
     -2:01.8.0 datatip:toggle (input.hidden-input)
     -2:01.7.0 core:move-right (input.hidden-input)
  6x -2:01.4.0 core:backspace (input.hidden-input)
     -1:53.9.0 core:save (input.hidden-input)
     -0:32.2.0 core:move-right (input.hidden-input)
     -0:30.7.0 core:save (input.hidden-input)
  2x -0:18.9.0 core:backspace (input.hidden-input)
     -0:17.9.0 toggle-quotes:toggle (input.hidden-input)
     -0:17.3.0 core:move-right (input.hidden-input)
     -0:17.1.0 core:backspace (input.hidden-input)
  3x -0:16.6.0 core:move-left (input.hidden-input)
     -0:15.6.0 core:backspace (input.hidden-input)
  2x -0:15.1.0 core:move-right (input.hidden-input)
     -0:14.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.5 
atom-ide-ui 0.13.0 
atom-terminal 0.8.0 
auto-update-packages 1.0.1 
autocomplete 0.47.0 
autocomplete-python 1.10.9 
browse 1.10.8 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.3.0 
colorful-json 1.1.0 
docblockr 0.13.7 
double-tag 1.5.0 
duplicate-lines-upward 1.1.3 
file-icons 2.1.22 
framer-syntax 1.1.0 
git-plus 8.0.0 
git-time-machine 2.1.0 
highlight-line 0.12.0 
highlight-selected 0.14.0 
hyperclick 0.0.0 
hyperlink-hyperclick 2.0.0 
ide-css 0.3.0 
ide-html 0.4.2 
ide-php 0.7.14 
ide-typescript 0.7.6 
ide-vue 0.1.9 
ide-yaml 0.4.3 
intentions 1.1.5 
js-hyperclick 1.13.3 
kirby-snippets 1.1.3 
language-cmake 1.1.0 
language-htaccess 0.2.0 
language-latex 1.1.1 
language-liquid 0.7.0 
language-markdown 0.26.0 
language-nginx 0.8.0 
language-vue 0.23.1 
latex 0.50.0 
less-than-slash 0.18.0 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
pdf-view 0.70.0 
pigments 0.40.2 
project-manager 3.3.6 
python-indent 1.1.5 
python-tools 0.6.9 
remote-atom 1.3.12 
split-diff 1.5.2 
styri-syntax 0.2.0 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
todo-show 2.3.0 
toggle-quotes 1.1.0 
```

**Comment by maxbrunsfeld** [comment]
@wottpal If you upgrade `toggle-quotes` to the latest version (v.1.1.1) does this still happen?

**Comment by wottpal** [comment]
> @wottpal If you upgrade toggle-quotes to the latest version (v.1.1.1) does this still happen?

Unfortunately yes :/

**Comment by Ben3eeE** [comment]
@maxbrunsfeld I can reproduce this if I run Atom 1.29 but not when running latest nightly.

**Comment by queerviolet** [comment]
Yeah, this is fixed by https://github.com/atom/atom/pull/17721.
